"""Initial migration: create users, cryptocurrencies, price_data, predictions tables

Revision ID: 0ebc9990b811
Revises: bdf7f90e03ac
Create Date: 2025-07-15 16:32:33.253387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebc9990b811'
down_revision: Union[str, None] = 'bdf7f90e03ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
